version: '3.6'
services:
  database:
    image: mysql:8.0.30-debian
    container_name: cosmos_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?err}
      - DB_BACKEND_USER_PASSWORD=${DB_BACKEND_USER_PASSWORD:?err}
      - DB_GRAFANA_USER_PASSWORD=${DB_GRAFANA_USER_PASSWORD:?err}
    networks:
      - cwnetwork
    restart: always
    volumes:
      # Mount for data directory and configuration
      - database:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  grafana:
    image: grafana/grafana-oss:9.2.1
    container_name: cosmos_grafana
    depends_on:
      - database
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:?err}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:?err}
      - GF_DEFAULT_APP_MODE=${GF_APP_MODE:?err}
    networks:
      - cwnetwork
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-plugins:/var/lib/grafana/plugins/cosmos-plugins/
      - ./provisioning:/etc/grafana/provisioning

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: base
    command: npm run dev
    #platform: linux/x86_64 # tentatively used for macOS M1 to compile grafana plugins
    container_name: cosmos_backend
    networks:
      - cwnetwork
    ports:
      - '10090:10090'
    restart: always
    volumes:
      # Install Grafana plugins
      - ./grafana-plugins:/grafana-plugins
      # For syncing dev changes
      - ./backend/src:/home/node/app/src
      - ./backend/tests:/home/node/app/tests
      # For accessing database stuff
      - ./.env:/home/node/app/.env
      # Access to COSMOS binaries
      - bin:/root/cosmos/bin
      - resources:/root/cosmos/resources

volumes:
  bin: {}
  resources: {}
  grafana_data: {}
  database: {}

networks:
  cwnetwork:
    name: cosmos_cwnetwork
    external: true
    driver: bridge

# TODO:
# Add port configurations, don't want to use common ports like 3000, 5000, etc.
